### ISSUE TITLE
Node v7でログインが壊れる

### ISSUE THREAD

**Issue by otofune** [misskey-delta/Misskey-Web#95]
```
{ Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
/home/otofune/Web/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:195:11)
    at ServerResponse.writeHead (/home/otofune/Web/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (/home/otofune/Web/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:159:8)
    at ServerResponse.end (/home/otofune/Web/node_modules/compression/index.js:102:14)
    at writeend (/home/otofune/Web/node_modules/express-session/index.js:261:22)
    at ontouch (/home/otofune/Web/node_modules/express-session/index.js:348:11)
    at tryCatcher (/home/otofune/Web/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/home/otofune/Web/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/home/otofune/Web/node_modules/bluebird/js/release/promise.js:564:21)
    at Promise._settlePromise0 (/home/otofune/Web/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/otofune/Web/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/otofune/Web/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/home/otofune/Web/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/home/otofune/Web/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/home/otofune/Web/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/otofune/Web/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/otofune/Web/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/otofune/Web/node_modules/bluebird/js/release/promise.js:636:18)
    at /home/otofune/Web/node_modules/bluebird/js/release/nodeback.js:45:21
    at handleCallback (/home/otofune/Web/node_modules/mongodb/lib/utils.js:96:12)
    at /home/otofune/Web/node_modules/mongodb/lib/collection.js:1048:5
    at /home/otofune/Web/node_modules/mongodb-core/lib/connection/pool.js:436:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
あかり died :(
```

**Comment by otofune** [comment]
P.S. Node v5で正常に動くように戻った

**Comment by otofune** [comment]
ugoita
